### ISSUE TITLE
No audio with some streams

### ISSUE THREAD

**Issue by adriadam10** [oxyroid/M3UAndroid#100]
I have no audio with some streams, that worked well on VLC

What are the supported audio formats?

**Comment by realOxy** [comment]
@adriadam10 Audio: Vorbis, Opus, Flac, Alac, pcm_mulaw, pcm_alaw, MP3, Amrnb, Amrwb, AAC, AC3, EAC3, dca, mlp, truehd
Video: H.264, HEVC, VP8, VP9

You can give me the playlist so that I can test it

**Comment by realOxy** [comment]
@adriadam10 Can you provide the link? If it is not convenient for you to send it here, you can also send it to me in a private message.
https://t.me/sortBy
