### ISSUE TITLE
More Playlist Source

### ISSUE THREAD

**Issue by oxyroid** [oxyroid/M3UAndroid#101]
- [X] M3U
- [X] Xtream API, https://xtream-ui.org/api-xtreamui-xtreamcode/
- [ ] Emby, https://dev.emby.media/doc/restapi/Browsing-the-Library.html#display-all-movies
- [ ] Plex
- [ ] Jellylin
- [ ] Aliyun Drive

**Comment by realOxy** [comment]
https://github.com/engenex/xtream-codes-api-v2/blob/main/%5BHow-To%5D%20Player%20API%20v2%20-%20Tutorials%20-%20Xtream%20Codes.pdf

**Comment by realOxy** [comment]
More about Xtream API: https://github.com/realOxy/xtream-codes-api-v2

**Comment by heberjeur** [comment]
Will you add directly EPG from Xtream link, or has this already been implemented?

![Screenshot_20240418-204536_Firefox](https://github.com/oxyroid/M3UAndroid/assets/11852634/8259827c-b231-49e1-8eab-191ef27a0209)

**Comment by oxyroid** [comment]
not impl yet. I do it once the basic epg is done
