### ISSUE TITLE
Set several channels from a playlist as favorites

### ISSUE THREAD

**Issue by sguinetti** [oxyroid/M3UAndroid#104]
**Is your feature request related to a problem? Please describe.**
For users coming from other apps that offer playlists with favorites, this feature request was made. It is somewhat complicated for a user, who has a list of favorites assigned in his previous list, to have to add step by step to mark several channels as favorites. In my case, I want to choose several channels when I press and hold one of them and then mark two or more as favorites (or remove from favorites).

**Describe the solution you'd like**
Include an option to choose multiple channels from context menu. The user can then choose whether to mark or unmark as favorite in the buttons at the top of the app.

Example:
![image](https://github.com/realOxy/M3UAndroid/assets/5572928/d65eaaf1-c953-4f1a-bb8e-5cfb9e2b3908)

**Describe alternatives you've considered**
I could say that on the Internet it appears as a "multiple-selection list". The design for reference is this video when selecting multiple files from a file manager: https://www.youtube.com/watch?v=GMSfXj30kbg

**Additional context**
The channel selection feature to mark or remove from favorites appears when entering a playlist.

In addition to setting channels as favorites, this feature would also be useful to hide channels.

**Comment by realOxy** [comment]
Umm,, I think it is unnecessary.
