### ISSUE TITLE
Thumbnails Cropped in Version 1.14.0-beta08

### ISSUE THREAD

**Issue by heberjeur** [oxyroid/M3UAndroid#111]
**Describe the bug**
Thumbnails are cropped in version 1.14.0-beta08 of the m3u application.

**To Reproduce**
1. Open the m3u application.
2. Navigate to live,vod or series sections.
3. Notice that thumbnails are cropped.

**Expected behavior**
Thumbnails should be displayed fully without any cropping.

**Screenshots**
This is a comparison of before/after
![Screenshot_20240316-234116_One UI Home](https://github.com/realOxy/M3UAndroid/assets/11852634/a2bebfdd-ddaf-401d-97ba-09a748170cef)

**Smartphone (please complete the following information):**
- Device: Samsung A50
- OS: Android 11
- Version: 1.14.0-beta08

**Additional context**

**Comment by realOxy** [comment]
Please try snapshot, I removed compact UI mode and make the default UI mode look better.

**Comment by heberjeur** [comment]
There is something wrong, I'm unable to access my account. Despite entering all my Xtream IPTV details such as playlist name, address, username, and password, my channels aren't appearing on the home screen.

https://github.com/realOxy/M3UAndroid/assets/11852634/7b0150dd-80f1-4d3b-a4a0-d96439addc15

**Comment by heberjeur** [comment]
Hi @realOxy 
I tried to bypass this bug by using the backup restore option. Through this method, I successfully displayed the channels.
Now, the thumbnails are correctly displayed, and the stream counter accurately updates after refreshing the page.

**Comment by realOxy** [comment]
https://github.com/realOxy/M3UAndroid/issues/116

**Comment by oxyroid** [comment]
@heberjeur Try snapshot.

**Comment by heberjeur** [comment]
@oxyroid it works now 🥳
