### ISSUE TITLE
Development suspended

### ISSUE THREAD

**Issue by oxyroid** [oxyroid/M3UAndroid#116]
Due to my recent poor mental state, the software will be suspended for maintenance for a while. I will resume development in about a month.

If you have any software errors or new feature proposals, you can continue to create or reply to issues. I will handle them after I officially return.

**Comment by heberjeur** [comment]
Thank you for your message. Your well-being is an absolute priority. We eagerly await your return as soon as possible. Take care of your self.

**Comment by sguinetti** [comment]
Thank you for letting us know of the progress. You've made several features in the application,  which gives a new use to the IPTV service, and it's good to take a break. Come back anytime.
