### ISSUE TITLE
does not play internet streams anymore

### ISSUE THREAD

**Issue by whatamesss** [oxyroid/M3UAndroid#117]
i'm not sure if/why this app was shutdown/broken...it's the only one i've found on f-droid that let's me play my home mp3 stream..

every other app stops playing on android13 when the screen locks. this one ingeniously blacks out the screen while employing a wakelock, getting around the issue! i was thrilled to find it!

however, as of late it just doesnt play.
if i load my m3u file that contains the url to my stream, it often does nothing at all (other than saying a subscription event has been scheduled?!?!)
sometimes it puts an item in my 'for-you' screen with the name of my playlist, but it contains zero streams.

i understand the author is taking a break...thats fine. can anyone else out there please comment?
oddly, i tried rolling back versions to the one that definitely worked and it doenst work either

**Comment by themodfatherinc** [comment]
try the m3u link on a pc and confirm it downloads. perhaps something changed server side. i am having no issues with m3u link testing

**Comment by whatamesss** [comment]
hi and thanks for your reply, the m3u was the same one i used with the previous version and was a simple one-line url.

i have since resoved the issue i was having with android and i've moved on from the m3u app..

i will mark this issue as closed as i will no longer be troubleshooting it
