### ISSUE TITLE
Favorite and Hidden Streams Reset After List Refresh

### ISSUE THREAD

**Issue by heberjeur** [oxyroid/M3UAndroid#119]
**Describe the bug**
After refreshing the TV, VOD, or series lists in the m3u player, the favorite and hidden streams settings are reset, causing inconvenience to users who have customized their preferences.

**To Reproduce**
1. Launch the m3u player app.
2. Navigate to either the TV, VOD, or series section.
3. Mark certain streams as favorite or hide specific streams.
4. Refresh the list by pulling down or using a refresh button.
5. Check that the favorite and hidden streams settings have been reset.

**Expected behavior**
The favorite and hidden streams settings should persist even after refreshing the lists, maintaining the user's customized preferences.

**Screenshots**

https://github.com/oxyroid/M3UAndroid/assets/11852634/562dbadd-3aab-460b-b202-5f6173af5b3b

**Smartphone (please complete the following information):**
- Device: Samsung A50
- OS: Android 11
- Version: A505F

**Additional context**

**Comment by oxyroid** [comment]
OK. I forgot keep them

**Comment by oxyroid** [comment]
Try snap

**Comment by heberjeur** [comment]
https://github.com/oxyroid/M3UAndroid/assets/11852634/cace1d91-8aee-499a-90a0-c25edec57878

**Comment by heberjeur** [comment]
> Try snap

I can't do anything. I can't access the configuration menu or add accounts.

**Comment by oxyroid** [comment]
Send the log to me

**Comment by oxyroid** [comment]
Try again, I downgrade some depends.

**Comment by heberjeur** [comment]
> Try again, I downgrade some depends.

It works now 😁

**Comment by heberjeur** [comment]
> Send the log to me

How to do that ?

**Comment by oxyroid** [comment]
> > Send the log to me
> 
> How to do that ?

If the app crashes, it will automatically redirect to the crash screen where you can view all historical log files. 

Simply click on the latest log (scroll down to the bottom if needed), save it as a file, and then you can send it here.

However, there's no need to do that now as this issue has been resolved.

**Comment by oxyroid** [comment]
Does this issue still exist on your device? If there is no problem, I will close it.
