### ISSUE TITLE
Add shortcut for "Pick a favorite"

### ISSUE THREAD

**Issue by sguinetti** [oxyroid/M3UAndroid#121]
**Is your feature request related to a problem? Please describe.**
I would like an option to see a random favorite channel by pressing the shortcut. It is an alternative option to "Recent", to see some content immediately from a channel that I may like. It is similar to "I'm Feeling Lucky" and encourages the undecided user to choose what to watch.

**Describe the solution you'd like**
Elaborate a shorcut called "Pick a favorite" (or "Select a favorite").

**Describe alternatives you've considered**
It is only a shorcut, it does not imply other options.

Preferably, the icon of this shortcut is a dice.

**Additional context**
See https://github.com/oxyroid/M3UAndroid/issues/44 for context about "Recent"

**Comment by oxyroid** [comment]
Great idea. I will add it recently.

**Comment by sguinetti** [comment]
I think that, in addition to the shortcut, a button like the shuffle buttons on music players could also be implemented to enable the "Pick a favorite" feature. This is very useful to pick a favorite in one click. When you want to change a channel, you also have to press the "Pick a favorite" button each time.

I find that if I set my initial screen as "favorite" and have the button, it changes the TikTok-like experience a lot. I start the application, press the button with the dice icon and play if this favorite channel convinces me or I choose another one at random until I find what I like.

**Comment by oxyroid** [comment]
I made a simple one.

**Comment by sguinetti** [comment]
Thank you for good news. I will test.

**Comment by sguinetti** [comment]
I like it. The button looks attractive in Favorites. However, when I press the button, the app chooses a channel in general (which I sense to be a bug being in the Favorites screen). I think it should have a button to randomly play all channels and a button to randomly play only favorite channels.

**Comment by oxyroid** [comment]
I added an option "Play Randomly Only From Favorite". 
And there is an issue for now, it maybe try to play a xtream series type channel and we know the series channel cannot be played directly(the episodes loader should be shown via network request, but this case is not suitable for that).
I will limit the type of channels played to only live (including m3u) or VOD types.

**Comment by sguinetti** [comment]
Two more suggestions:
* Add as shorcut from the launcher (like Recentely shorcut).
* Let play randomly ignore channels hidden by the user.

**Comment by sguinetti** [comment]
I find another "glitch" if there is no playlist in the app. Instead of a black background, an error message "Cannot play randomly from without playlist added" should appear. This message is similar with the “Add a playlist” button.

**Comment by oxyroid** [comment]
We should not add too much shortcuts, because some launchers at most show 3 or 4 shortcuts for one application.
And I think it is a correct behavior that the player is not playing if there is no streams when we entered it by "play randomly".
