### ISSUE TITLE
Cannot edit a playlist with longer user-agent text

### ISSUE THREAD

**Issue by sguinetti** [oxyroid/M3UAndroid#122]
**Describe the bug**
After adding a user-agent with a lot of text and saving, the edit button disappears. Which makes it difficult to edit again. This applies in portrait and landscape mode.

**To Reproduce**
1. Select a list and edit
2. Add a longer user-agent
3. Apply changes

**Expected behavior**
The edit button disappears and it is not possible to edit again.

**Screenshots**
![IMG_20240420_114541_097](https://github.com/oxyroid/M3UAndroid/assets/5572928/b7a9c49c-882e-4bb6-9354-30b3a27bc616)

**Smartphone (please complete the following information):**
- Device: Galay A04
- OS: Android 14
- Version  1.14.0-beta10 (app)

**Comment by oxyroid** [comment]
OK. I will fix that.
