### ISSUE TITLE
Option to enable "cache while playing" only for movies and series (or non-live videos) + HLSDownloader for m3u offline streaming

### ISSUE THREAD

**Issue by sguinetti** [oxyroid/M3UAndroid#123]
**Is your feature request related to a problem? Please describe.**
I have noticed that "cache while playing" is useful for watching movies and series in Xtream (or M3U files that only contain time-lapse videos and not live). So, I am happy that this direction has been taken. However, this feature is complicated for live transmissions because only the first 30 seconds are displayed and activating "cache while playing" ends up making it difficult to view live streaming channels (because the image gets stuck).

**Describe the solution you'd like**
My solution is to have an option to view "cache while playing" in these circumstances:
* Use the cache for m3u8 files in movies (or VOD services)  like this sample: https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8 ([more samples](https://ottverse.com/free-hls-m3u8-test-urls/) in this web). In the case of videos from Xtream, this also applies
*  Do not use the cache on 24/7 live channels such as NASA TV: https://nasa-i.akamaihd.net/hls/live/253565/NASA-NTV1-Public/master.m3u8

**Describe alternatives you've considered**
It is a third option instead of activating or deactivating the feature completely.

**Additional context**
The caching issue makes more sense for rewatchable videos than for live channels. Videos need to be cached so they don't reload again and waste bandwidth. On the other context, live channels are always refreshed every moment and also take up unnecessary space, so the cache loses sense in that case.

P.S.: The option to set the cache limit is missed. This option is important for cell phones with limited storage. I would appreciate if it is added in the settings. Like this image from InnerTune:

![image](https://github.com/oxyroid/M3UAndroid/assets/5572928/503a3c67-7700-43ee-8dcc-9dc203f17ca0)

P.S. 2: Also, because you are using androidx-media3-media3-exoplayer-hls, I have found a HLS Downloader section, which can be written in Kotlin. I think, it is an alternative to the androidx.media3.datasource.cache library cache  (which does not affect formats other than m3u/m3u8). This option would help with offline viewing of HLS content and maybe help solve the problem (bug) when the image gets stuck.

More info: https://developer.android.com/reference/kotlin/androidx/media3/exoplayer/hls/offline/HlsDownloader

(edited for new lines)

**Comment by oxyroid** [comment]
As far as I know now, we cannot know whether the streaming media is fixed length before it is ready, but whether to use caching needs to be decided before loading it. In addition, for some live streams, even if we specify not to cache dynamic length video streams, the framework will still cache them.

**Comment by sguinetti** [comment]
I have checked on the Apple forum about the differences between the three types that HLS can carry. I quote the bottom line:

```
- VOD - has EXT-X-PLAYLIST-TYPE:VOD; contains all segments; has an EXT-X-ENDLIST tag
- EVENT - has EXT-X-PLAYLIST-TYPE:EVENT; periodically refetched, each time getting longer; eventually adds an EXT-X-ENDLIST tag
- LIVE - does not have EXT-X-PLAYLIST-TYPE; periodically refetched, with sliding window; NEVER gets an EXT-X-ENDLIST tag.
```

I believe, I am not an encoding specialist, that if the player identifies "EXT-X-ENDLIST" in a m3u file it could perform the caching process by its fixed length. Maybe it's complicated, but that could determine whether one video is live and one is VOD.

**Comment by oxyroid** [comment]
The problem is that many playlists don't follow this standard.
