### ISSUE TITLE
Channel icon are broken if they are not in the same size as the box in TV.

### ISSUE THREAD

**Issue by mohitkyadav** [oxyroid/M3UAndroid#127]
**Describe the bug**
I have a playlist with channel icons which are not in the rectangular format. They are transparent images with the exact dimensions of the channel. For example here's one for sky news:

![sky](https://github.com/tv-logo/tv-logos/blob/main/countries/united-kingdom/hd/sky-news-hd-uk.png?raw=true)

**To Reproduce**
1. Add a playlist with any items, set the icon/poster to this: `https://github.com/tv-logo/tv-logos/blob/main/countries/united-kingdom/hd/sky-news-hd-uk.png?raw=true`

**Expected behavior**
The channel box should not crop the image on TV. It should work how it works in the mobile app.

**Screenshots**
![ss](https://github.com/oxyroid/M3UAndroid/assets/25580776/4797e5a5-8417-47ad-a461-0c6f563101b5)

**Smartphone (please complete the following information):**
 - Device: Android tv
 - OS: Android 12
 - Version 1.14 beta

**Additional context**

**Comment by oxyroid** [comment]
OK. I will fix it

**Comment by mohitkyadav** [comment]
Thank you @oxyroid , it's a great app. I tried contributing myself but I'm not experienced in Kotlin. That's not the biggest issue, I'm having this issue right now, When I make a change in the code, the changes do not hot reload, do you know how to enable that or I'll have to rerun it even after changing one line. Maybe you can tell me how to fix these, will make the development hella easier.

I'm using Android studio on MacOs + Android Emulator.

**Comment by oxyroid** [comment]
You can check this.

https://developer.android.com/develop/ui/compose/tooling/iterative-development#live-edit

And I think it is a very unstable feature for now. So I don't use it and rerun application after changing one line. 🙃

**Comment by mohitkyadav** [comment]
> You can check this.
> 
> https://developer.android.com/develop/ui/compose/tooling/iterative-development#live-edit
> 
> And I think it is a very unstable feature for now. So I don't use it and rerun application after changing one line. 🙃

Wow, it must have been very tough so far 😅, respect 🙌 . Okay I'll try the live edit thanks.
