### ISSUE TITLE
I can't import m3u local list

### ISSUE THREAD

**Issue by heberjeur** [oxyroid/M3UAndroid#132]
**Describe the bug**
When attempting to open an m3u file in the M3U Android app, users encounter an error displaying a blank URL.

**To Reproduce**
1. Go to settings, playlist management.
2. Click on local storage.
3. Choose m3u file.
4. Click on subscribe.
5. Encounter error: blank URL.

**Expected behavior**
Upon subscribing to an m3u file, the expected behavior is for the file to be successfully loaded without encountering any errors.

**Screenshots**
![Screenshot_20240427-032003_M3U](https://github.com/oxyroid/M3UAndroid/assets/11852634/961d9c89-80a9-4405-ab3a-80cf46529d44)

**Smartphone (please complete the following information):**
- Device: Samsung A50
- OS: Android 11

**Additional context**
No additional context provided.

**Comment by oxyroid** [comment]
Try snapshot

**Comment by heberjeur** [comment]
> Try snapshot

Not yet, I can't see my channels

**Comment by oxyroid** [comment]
Try again:)

**Comment by heberjeur** [comment]
It works correctly now 😁
