### ISSUE TITLE
 AndroidTV EPG not working

### ISSUE THREAD

**Issue by PhynixP** [oxyroid/M3UAndroid#145]
**Describe the bug**
With a **AndroidTV** Box EPG Data not working
On a Samsung Galaxy S22 / S24 EPG Working fine.

**To Reproduce**
If you have installed EPG Data select the Channellist.
Then you don't see the EPG's 

**Smartphone (please complete the following information):**
 - Device: Amazon Fire TV Cube 3
 - OS: Android 8
 - Version (1.14 Beta 11) and (1.14 Beta 11 (Master-Tag) self compiled)

**Comment by oxyroid** [comment]
Yes, the new feature adaptation on the TV side is always slower than that on the mobile side. We usually consider adapting it to the TV after the new feature is stable.

**Comment by oxyroid** [comment]
Have a try the latest snapshot package. You can get its download link in README.md

**Comment by PhynixP** [comment]
thank you oxyroid
