### ISSUE TITLE
Add TV Reminder from EPG list

### ISSUE THREAD

**Issue by sguinetti** [oxyroid/M3UAndroid#153]
**Is your feature request related to a problem? Please describe.**
Taking advantage of the potential of EPGs, some cable providers use TV reminders. This is useful to notify that the program is about to start, especially if it is live or premiering. This is useful in directly accessing the channel without having to manually search the channel list.

In my case, using program reminders helps me avoid forgetting about the program or series I usually like.

**Describe the solution you'd like**
Implement the “Reminder” option to the program that is useful to the user from the Player Panel. The smartphone will notify the user when the program is about to start.

**Describe alternatives you've considered**
It can be implemented in several ways. In this sense from the Player Panel, the user can press and hold the program from the EPG section to immediately mark it as a “Reminder”. A bell icon is used to identify it.

Then, the users will be able to check from a section where it is shown which programs them put in “Reminder” to check if it is in the list orthem wants to remove it. Perhaps Reminder can be better used if you add an option to notify every day (Monday-Friday, every week, and so on).

**Additional context**
See example from Claro TV (in spanish): https://www.youtube.com/watch?v=ReS6RPwM7Kc&t=139s
Other example (from Tata, with english subtitles): https://www.youtube.com/watch?v=3h81hT_WpRk

**Comment by sguinetti** [comment]
The feature can be managed from a section or a button from “For you” or from the settings. In addition, the option to add random programs from favorite channels to the reminders can be incorporated in this section. See concept:

![image](https://github.com/oxyroid/M3UAndroid/assets/5572928/6f0daa15-73f3-4a3f-a1b3-7e510858e13b)

**Comment by oxyroid** [comment]
Completed.
