### ISSUE TITLE
I think it will be better if adding a button to rotate the screen between landscape and Portrait.

### ISSUE THREAD

**Issue by Apollo-yeah** [oxyroid/M3UAndroid#155]
**Is your feature request related to a problem? Please describe.**
- Sometimes I will use my phone to watch the IPTV but I don't like setup my phone as auto rotate with device. However, now the app only support rotate as landscape by auto.

**Describe the solution you'd like**
Add a button to rotate the screen in the location of Top-Right. I think it will more convenient to control.

Thanks!

**Comment by Apollo-yeah** [comment]
Sorry, When I enter the settings I find the function! 
But it's in the secondary menu of **Optional Player Features**, it seems too deep, hahaha!

**Comment by oxyroid** [comment]
Phew :P
