### ISSUE TITLE
Screen shakes very fast

### ISSUE THREAD

**Issue by PhynixP** [oxyroid/M3UAndroid#158]
**Describe the bug**
Screen shakes very fast from left to right

**To Reproduce**
1- After installing the App, click on Settings (icon).
2- Then go to the right to the functions.
3- The screen shakes very quickly from left to right

**Smartphone (please complete the following information):**
- Device: [Nvidea Shield and Amazon Fire TV Cube 3]
- OS: [ Shield  Android 13 and on FireTV Cube Android 8]

**Comment by PhynixP** [comment]
If you compile and install this version, it works fine [4f917c1](https://github.com/oxyroid/M3UAndroid/commit/4f917c1d6bdb89671220a3b93b1f157088ddbc6f)

PhyniX

**Comment by oxyroid** [comment]
Can you record how it shakes? I just upgraded a compose list-detail layout dependency.

**Comment by oxyroid** [comment]
Record a video to show it to me.

**Comment by oxyroid** [comment]
Fixed, check again.

**Comment by PhynixP** [comment]
Hey oxyroid,
i have test it.
Now it works fine on Emulator,Shield and FireTV
Thanks for this

**Comment by PhynixP** [comment]
The shakeing is over and working fine.
But the m3u list do not open anymore.
After click on the M3U list the screen is online white.
I thing the app is crashed.

PhyniX

**Comment by oxyroid** [comment]
Video Plz

**Comment by PhynixP** [comment]
Hello oxyroid,
i have made a video but it is too big for github.
i have upload to file.io  https://file.io/SoLWvdFuX04K

**Comment by oxyroid** [comment]
I upgraded the latest compose-1.7 prerelease recently, they [Renamed BringIntoView to ScrollIntoView](https://android-review.googlesource.com/c/platform/frameworks/support/+/2954617), but they did not do that in latest compose-tv-foundation prerelease.

I decided to use the SNAPSHOT compose-tv build temporarily. It may fix the crash on tv devices.

Have a try the SNAPSHOT package again!

**Comment by oxyroid** [comment]
Update: I found the official compose tv example removed the compose tv foundation dependency and the compose foundation 1.7 added some adaptations for tv devices.
So I also do it as well. Also keep the reproduction.

**Comment by PhynixP** [comment]
Nice! It works fine now.
I can't find bugs anymore.
