### ISSUE TITLE
INSTALL_FAILED_OLDER_SDK when installing on Fire TV Stick 2nd Gen

### ISSUE THREAD

**Issue by tandy-1000** [oxyroid/M3UAndroid#162]
**Check before feedback**
- [x] I checked the other issues to ensure no one has mentioned it yet.
- [x] I made sure the bug can be reproduced in the [SNAPSHOT](https://nightly.link/oxyroid/M3UAndroid/workflows/android/master/artifact.zip) application package.

**Describe the bug**
The application can't be installed on older android versions.

**To Reproduce**

1. Try install on Fire TV Stick 2nd Gen
2. Error: INSTALL_FAILED_OLDER_SDK 

**Expected behavior**
The app should install.

**Smartphone (please complete the following information):**

- Device: Fire TV Stick 2nd Gen
- OS: Lineage 12/Android 5.1
- Version: 1.14.0-rc01

**Comment by oxyroid** [comment]
Unfortunately, this software only supports devices with Android 8 and above.
