### ISSUE TITLE
unable to parse some epg

### ISSUE THREAD

**Issue by rhjdvsgsgks** [oxyroid/M3UAndroid#164]
**Check before feedback**
- [x] I checked the other issues to ensure no one has mentioned it yet.
- [x] I made sure the bug can be reproduced in the [SNAPSHOT](https://nightly.link/oxyroid/M3UAndroid/workflows/android/master/artifact.zip) application package.

**Describe the bug**
no programmes even after sync manually

**To Reproduce**

1. add epg https://raw.githubusercontent.com/BurningC4/Chinese-IPTV/master/guide.xml ~or https://iptv-org.github.io/epg/guides/cn/tv.cctv.com.epg.xml~
3. link to a playlist
4. sync programme

**Expected behavior**
able to see the timetable

**Screenshots**

**Smartphone (please complete the following information):**

- Device: any
- OS: any
- Version  1.14.0-rc01

**Additional context**
`java.time.format.DateTimeParseException: Text '20240613161500' could not be parsed at index 14` with first epg above

~`org.xmlpull.v1.XmlPullParserException: unresolved: &middot; (position:TEXT @6:35 in java.io.InputStreamReader@dcea59e)` with latter~ caused by a deleted link

**Comment by oxyroid** [comment]
fixed
