### ISSUE TITLE
Can't play live stream

### ISSUE THREAD

**Issue by PPECHENOT** [oxyroid/M3UAndroid#176]
**Describe the bug**
[2004] ERROR_CODE_IO_BAD_HTTP_STATUS on :
http://king365-tv.com:2103/play/live.php?mac=00:1A:79:4F:50:DD&stream=1154&extension=ts

**Expected behavior**
Add VLC codecs in player options

**Smartphone (please complete the following information):**
- Devices: Galaxy Tab S5e and Xiaomi MiStick TV
- OS: Android 11 and Android 9

**Comment by oxyroid** [comment]
502 http error code

**Comment by PPECHENOT** [comment]
> 502 http error code

No problem and no error in others players (Ultimate IPTV playlist loader, IPTV pro...) !

**Comment by oxyroid** [comment]
Consider add a user-agent?
