### ISSUE TITLE
EPG is not working

### ISSUE THREAD

**Issue by DumberSoft** [oxyroid/M3UAndroid#178]
I have seen that the EPG is not working, since I am using an Xtream UI but it is still not working, since I have put the URL in the EPG but anyway, some help please.

**Comment by oxyroid** [comment]
If you are using Xtream, you needn't put EPG url manually. Just press Xtream Live Playlist. Once a dialog appears, click the pencil icon. You will see the configuration screen. Click Sync Programmes Button then the EPG will be downloaded.

**Comment by DumberSoft** [comment]
Thx
