### ISSUE TITLE
Brightness & Volume gestures only work when controls are displayed

### ISSUE THREAD

**Issue by dymarow** [oxyroid/M3UAndroid#190]
**Bug**

https://github.com/user-attachments/assets/42a2e241-597a-4d0b-8ba9-d9f94a9374a3

**Expected behavior**

https://github.com/user-attachments/assets/180bbeb6-3739-4a9b-a67b-ee27b634d57b

**Information**

- Device: Pixel 8a
- OS: Android 15 QPR1
- M3UAndroid version 1.14.0-rc03 / 1.14.0-rc03-snapshot[09081355]

**Comment by oxyroid** [comment]
fixed in #200, thanks @tungnk123
