### ISSUE TITLE
EPG errors 

### ISSUE THREAD

**Issue by thomraider12** [oxyroid/M3UAndroid#203]
**Check before feedback**
- [ ] I checked the other issues to ensure no one has mentioned it yet.
- [ ] I made sure the bug can be reproduced in the [SNAPSHOT](https://nightly.link/oxyroid/M3UAndroid/workflows/android/master/artifact.zip) application package.

**Describe the bug**
I have selected the EPG I wanted in my case, I clicked the button sync programmes, but multiple errors ocurred in the M3U, while in other players, everythings fine. It says "Unexpected token (position:TEXT ý7zXZ?F!...@2:36 in java.io.Input...)"

**Expected behavior**
I expected it to load the EPG's normally.

**Screenshots**
![Screenshot_20241016_191549_M3U](https://github.com/user-attachments/assets/5a9319b8-9847-4208-a502-add906153373)

**Smartphone (please complete the following information):**

- Device: [Samsung Galaxy A54 5G]
- OS: [Android 14]
- Version [1.14.0-rc03 (143)]

**Additional context**

**Comment by oxyroid** [comment]
It seems you are trying to pause programmes from the playlist link but not epg link.

**Comment by thomraider12** [comment]
How do I fix then

**Comment by oxyroid** [comment]
EPG link should end with .xml or .xml.gz

**Comment by thomraider12** [comment]
> EPG link should end with .xml or .xml.gz

Oh, thats why. Thank you. So I would suggest to add .xz support, if possible
