### ISSUE TITLE
Add EPG support (XML)

### ISSUE THREAD

**Issue by wuniversales** [oxyroid/M3UAndroid#52]
Good morning,
I miss being able to see the guide with what you are currently doing.
When adding a list, add an optional field for the EPG of the list.
Once set up, show on each channel, a line at the bottom indicating the progress of the current program, and show what they are currently doing.
Also to be able to know somehow what you have done and what you are going to do next, greetings!

**Comment by realOxy** [comment]
Hi, Can you provide sample EPG and m3u urls for development and debugging?

**Comment by sguinetti** [comment]
@realOxy If you mean to implement EPG, I find it interesting that each channel has its own small information guide to know which program or movie the user is watching. The only functional EPG is from TDT Channels (https://www.tdtchannels.com/listas) but it works only with the M3U lists of TDT Channels.

**Comment by wuniversales** [comment]
There are many more lists with EPG.
https://i.mjh.nz 
This link is a gold mine for everyone....
Apart from this I mean to be able to show it like this, an option to see the whole guide, and in the second part of the gif you see some channels with a progress bar below, below the channel itself it also comes out what they are doing.
Greetings

![VID_20240101_203928(1)](https://github.com/realOxy/M3UAndroid/assets/48658161/3c1395a4-132c-46b6-aede-f713192a0f27)

**Comment by oxyroid** [comment]
Completed.
