### ISSUE TITLE
Improved readability when the app is in split-screen mode

### ISSUE THREAD

**Issue by sguinetti** [oxyroid/M3UAndroid#65]
**Is your feature request related to a problem? Please describe.**
The PIP (Zapping Mode) function works quite well. However, some phones offer the split-screen option for multitasking. In this case, the user can in a split window take advantage of the possibility to "switch channels" while doing another activity (such as chatting to coordinate watching a single channel in a group, watching news coverage on a certain topic, and so on). I also find it useful to use split mode to manage DLNA mode in one window, while sharing the channel's web page on the TV to check the news beyond the EPG in other window.

**Describe the solution you'd like**
If possible, the preview of the letters should be improved when the app is in split screen mode. In some cases, the list is not readable to know the channels when it is distributed in 2 channels per row (changed rom "God Mode").

**Describe alternatives you've considered**
The most possible is to reduce typography size and decrease spaces to improve the user experience.

**Additional context**
An example of readability is shown in the screenshots.

![image](https://github.com/realOxy/M3UAndroid/assets/5572928/4bb1705d-466a-4246-a37a-67db438c6932)

**Comment by realOxy** [comment]
@sguinetti Maybe we should keep at most 1 item per row when compact mode is on.

**Comment by sguinetti** [comment]
Sincerely yes. I think, based on what I read the documentation, it's a landscape window but, being a smartphone, it's much smaller and takes up less screen space. I find some documentation: 
* Material 2: https://m2.material.io/design/platform-guidance/android-split-screen.html#layout
* Source by Android: https://source.android.com/docs/core/display/split-screen

**Comment by realOxy** [comment]
Is your idea to provide different options for Zapping Mode? They are: disable, picture-in-picture mode, split-screen mode

**Comment by sguinetti** [comment]
I don't understand your idea, but I will try to explain it to you. The app has a split-screen mode (that is implemented when changing apps from the system) regardless of whether Zapping mode of the app is activated or not. Because I'm talking about improving the display of the lists and text, as I showed in the screenshots. 

So, if you're talking about split mode as an alternative to Zapping mode (I guess to see more of the stream), that's not exactly what I'm talking about.
