### ISSUE TITLE
Support basic authentication

### ISSUE THREAD

**Issue by tetricky** [oxyroid/M3UAndroid#72]
I have some self provided streams, which are behind a reverse proxy, with authentication required.

I would like to be able to supply basic authentication in the form:

```
http://user:password@domain.com/
```

I've tried this, and it doesn't appear to be supported currently.

**Comment by realOxy** [comment]
Please tell me more about this, I didn't understand well

**Comment by tetricky** [comment]
In order to provide some sort of authentication to publicly accessible streams, but to retain cross platform support of .ogg streams, there is a narrow range of options. 

.ogg is not natively,  or easily,  supported on ios, but basic authentication through passing credentials in the URL  are supported by VLC, which in turn supports .ogg on a cross platform basis.

Such streams can therefore be accessed cross platform without re-encoding or multiple endpoints. They are also available in the browser on android and Linux using [url credentials](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#access_using_credentials_in_the_url).

It would be handy to be able to manage and access them in m3u (I have my radio favorites in a playlist, which I use as an internet radio).  Currently those with URL credentials don't play.

**Comment by realOxy** [comment]
Please try 1.14.0-alpha13

**Comment by tetricky** [comment]
1.14.0-alpha13 has just come through on Fdroid for me. When auto reconnect is set to 'ALWAYS' streams now continue restarting after what would previously be halted as 'COMPLETED'.

So that looks like the behaviour I was looking for. Thank you very much!

**Comment by realOxy** [comment]
> 1.14.0-alpha13 has just come through on Fdroid for me. 
> 
> 
> 
> Looking at streams with basic auth in the url I'm getting:
> 
> 
> 
> IDLE
> 
> [2004] ERROR_CODE_IO_BAD_HTTP_STATUS

Have you try to play the channel  in any other player? Could you share the link for me?

In addition, Please test it in latest package which is published in Github release page.

**Comment by realOxy** [comment]
@tetricky Thanks. I have successfully played the audio correctly on my local computer, you can turn it off. Also, I would like to know if this should be the default identity verification way. Is there any way for me to determine which verification way a channel needs to use?

**Comment by realOxy** [comment]
Please try the latest snapshot package. Is it worked for you?

**Comment by tetricky** [comment]
I've just had the opportunity to try on v1.14.0-beta04 (update yesterday).

Now it just says "BUFFERING" and then "IDLE", without the error message - but the stream doesn't play.
