### ISSUE TITLE
F-Droid not reproducible

### ISSUE THREAD

**Issue by linsui** [oxyroid/M3UAndroid#95]
**Describe the bug**
See https://gitlab.com/linsui/fdroiddata/-/jobs/6195627756. The library list generated by aboutLibraries in your apk is empty.

**Comment by realOxy** [comment]
I think that because I enabled the offline-mode of aboutLibraries. Now I have disable it and the generated list is appeared in my smartphone.

**Comment by linsui** [comment]
Then I just wait for the next version? Do you know why the list is generated in our build?

**Comment by linsui** [comment]
Since you enabled splitAbi, should we also do that?

**Comment by realOxy** [comment]
I think abi split is necessary because the fully package is a little big

**Comment by realOxy** [comment]
Yes, just waiting for next release

**Comment by linsui** [comment]
We need different version codes for different abis, i.e. 1060 for universal and 1061, 1062, 1063, 1064 for different abis.

**Comment by realOxy** [comment]
Well, then let’s not make abi split for f-droid.

**Comment by linsui** [comment]
:ok_hand:

**Comment by linsui** [comment]
It fails again. There is an item for com.github.anilbeesetti.nextlib:nextlib-media3ext in our apk but not yours.

**Comment by realOxy** [comment]
I have made "codec" flavor, the lite codec one has not nextlib item but the rich codec has.
Did you compare the apk with the right flavor? richCodec + stableChannel

**Comment by linsui** [comment]
There is no other difference so I thought it's the correct flavor.

**Comment by realOxy** [comment]
Which apk file in the release page you compared with?

**Comment by linsui** [comment]
https://github.com/realOxy/M3UAndroid/releases/download/v1.14.0-beta08/1.14.0-beta08_universal.apk

**Comment by realOxy** [comment]
Can you provide the compare result?

**Comment by linsui** [comment]
[1.14.0-beta08_universal.apk.html.zip](https://github.com/realOxy/M3UAndroid/files/14627324/1.14.0-beta08_universal.apk.html.zip)

**Comment by realOxy** [comment]
Oh, you mean about-library. I will replace it.

**Comment by licaon-kter** [comment]
```
│ │ │   --- 1.14.0-beta13_universal/smali/mb/a.smali
│ │ ├── +++ com.m3u.androidApp_139/smali/mb/a.smali
│ │ │ @@ -24,19 +24,19 @@
│ │ │  .method public constructor <init>(Landroid/app/Application;)V
│ │ │      .locals 2
│ │ │  
│ │ │      invoke-direct {p0}, Ljava/lang/Object;-><init>()V
│ │ │  
│ │ │      iput-object p1, p0, Lmb/a;->a:Landroid/app/Application;
│ │ │  
│ │ │ -    const-string p1, "1.14.0-beta11"
│ │ │ +    const-string p1, "1.14.0-beta13"
│ │ │  
│ │ │      iput-object p1, p0, Lmb/a;->b:Ljava/lang/String;
│ │ │  
│ │ │ -    const/16 p1, 0x89
│ │ │ +    const/16 p1, 0x8b
│ │ │  
│ │ │      iput p1, p0, Lmb/a;->c:I
│ │ │  
│ │ │      const-string p1, "stableChannelRichCodec"
│ │ │  
│ │ │      const-string v0, "snapshotChannel"
```
for https://github.com/oxyroid/M3UAndroid/releases/tag/v1.14.0-beta13

**Comment by licaon-kter** [comment]
and today https://gitlab.com/fdroid/fdroiddata/-/jobs/6886142345#L3331

fyi https://gitlab.com/fdroid/fdroiddata/-/commit/f83b060e4d0c6b990b034cbb007554e8b45aff00
